apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: threescale-test
spec:
  destination:
    namespace: threescale-testing
    server: https://kubernetes.default.svc
  project: default
  source:
    path: 3scale/
    repoURL: <your-own-repo-url>
    targetRevision: test
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
